---
env:
  ELASTICSEARCH_URL: http://localhost:9200/
jobs:
  test:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    name: '${{ matrix.name }}'
    runs-on: "${{ fromJSON('[\"ubuntu-latest\", \"ubuntu-20.04-xl\"]')[github.repository == 'github/docs-internal'] }}"
    steps:
      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - if: "${{ matrix.name == 'search' || matrix.name == 'languages' }}"
        uses: ./.github/actions/setup-elasticsearch
      - uses: ./.github/actions/node-npm-setup
      - if: "${{ github.repository == 'github/docs-internal' }}"
        uses: ./.github/actions/get-docs-early-access
        with:
          token: '${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}'
      - if: "${{ matrix.name == 'fixtures' }}"
        name: Check the test fixture data (if applicable)
        run: 'npm run copy-fixture-data -- --check'
      - env:
          ROOT: src/fixtures/fixtures
        if: "${{ matrix.name == 'fixtures' }}"
        name: Check the test fixture content (if applicable)
        run: |
          # If either of these fail, it means our fixture content's internal
          # links can and should be updated.
          npm run update-internal-links -- --dry-run --check --strict \
            src/fixtures/fixtures/content \
            --exclude src/fixtures/fixtures/content/get-started/foo/typo-autotitling.md \
            --exclude src/fixtures/fixtures/content/get-started/foo/anchor-autotitling.md
          npm run update-internal-links -- --dry-run --check --strict \
            src/fixtures/fixtures/data
      - if: "${{ matrix.name == 'languages' }}"
        name: Clone all translations
        uses: ./.github/actions/clone-translations
        with:
          token: '${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}'
      - env:
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          HEAD: '${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}'
          PR: '${{ github.event.pull_request.number }}'
        if: "${{ matrix.name == 'content-linter' }}"
        name: Gather files changed
        run: |
          # Find the file diff in the pull request or merge group
          # If its a pull request, use the faster call to the GitHub API
          # For push, workflow_dispatch, and merge_group, use git diff
          if [ -n "$PR" ]
          then
            echo __ running gh pr diff __
            DIFF=`gh pr diff $PR --name-only`
          elif [ -n "$HEAD" ]
          then
            echo __ running git fetch main __
            git fetch origin main --depth 1
            echo __ running git diff __
            DIFF=`git diff --name-only origin/main`
          else
            echo __ no head, empty diff __
            DIFF=''
          fi
          # So we can inspect the output
          echo __ DIFF found __
          echo $DIFF
          
          # So that becomes a string like `foo.js path/bar.md`
          # Must do this because the list of files can be HUGE. Especially
          # in a repo-sync when there are lots of translation files involved.
          echo __ format, write to get_diff_files.txt __
          echo $DIFF | tr '\n' ' ' > get_diff_files.txt
      - uses: ./.github/actions/cache-nextjs
      - name: Run build script
        run: npm run build
      - if: "${{ matrix.name == 'redirects' }}"
        uses: ./.github/actions/warmup-remotejson-cache
      - env:
          ROOT: src/fixtures/fixtures
        if: "${{ matrix.name == 'pageinfo' }}"
        uses: ./.github/actions/precompute-pageinfo
      - if: "${{ matrix.name == 'search' || matrix.name == 'languages' }}"
        name: Index fixtures into the local Elasticsearch
        run: npm run index-test-fixtures
      - env:
          CHANGELOG_CACHE_FILE_PATH: src/fixtures/fixtures/changelog-feed.json
          DIFF_FILE: get_diff_files.txt
          ENABLED_LANGUAGES: "${{ matrix.name == 'languages' && 'all' || '' }}"
          ROOT: "${{ (matrix.name == 'fixtures' || matrix.name == 'pageinfo' || matrix.name == 'landings' ) && 'src/fixtures/fixtures' || '' }}"
          TRANSLATIONS_FIXTURE_ROOT: "${{ (matrix.name == 'fixtures' || matrix.name == 'pageinfo') && 'src/fixtures/fixtures/translations' || '' }}"
        name: Run tests
        run: 'npm test -- src/${{ matrix.name }}/tests/'
    strategy:
      fail-fast: false
      matrix:
        exclude:
          - isPrivateRepo: false
            name: languages
        isPrivateRepo:
          - "${{ github.repository == 'github/docs-internal' }}"
        name:
          - archives
          - assets
          - audit-logs
          - automated-pipelines
          - changelogs
          - color-schemes
          - content-linter
          - content-render
          - data-directory
          - early-access
          - events
          - fixtures
          - frame
          - ghes-releases
          - github-apps
          - graphql
          - landings
          - languages
          - learning-track
          - observability
          - pageinfo
          - products
          - redirects
          - release-notes
          - rest
          - search
          - shielding
          - versions
          - webhooks
          - workflows
    timeout-minutes: 60
name: Test
on:
  merge_group: ~
  pull_request: ~
  workflow_dispatch: ~
permissions:
  contents: read
  pull-requests: read
