name: Matrix Results V2
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
      
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest", "windows-2019"],
              "perl": ["5.38.0", "5.36.0"]
            }
        run: |
          jq -rn 'env.DATA | fromjson | @json "matrix=\(.)"' > $GITHUB_OUTPUT
  build:
    needs:
      - setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    concurrency:
    # If the CI run is for a PR, allow a single concurrent run per PR and cancel
    # all other runs for the same PR (e.g., if the PR was rebased) even when
    # those runs are for different commits.  If the CI run is for anything else
    # (push, workflow_dispatch, schedule), allow a single concurrent run per
    # commit and cancel other runs for the same commit.
    #
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{matrix.os}}-${{matrix.perl}}
      cancel-in-progress: true
    steps:
      - id: test1
        name: Get Perl Version
        run: |
          perl -V > build-output-${{strategy.job-index}}.txt
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: build-output-${{strategy.job-index}}
          path: build-output-${{strategy.job-index}}.txt
          if-no-files-found: error
          retention-days: 1
          
  test:
    needs:
      - setup
      - build
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    concurrency:
    # If the CI run is for a PR, allow a single concurrent run per PR and cancel
    # all other runs for the same PR (e.g., if the PR was rebased) even when
    # those runs are for different commits.  If the CI run is for anything else
    # (push, workflow_dispatch, schedule), allow a single concurrent run per
    # commit and cancel other runs for the same commit.
    #
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{matrix.os}}-${{matrix.perl}}
      cancel-in-progress: true
    steps:
      - id: test1
        name: Pretend we are doing something
        run: |
          echo '${{matrix.os}}:${{matrix.perl}} ......... ok' > output_${{strategy.job-index}}.txt
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: test-output-${{strategy.job-index}}
          path: test-output-${{strategy.job-index}}.txt
          if-no-files-found: error
          retention-days: 1
          
  summarize-build:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report build results
        run: |
          grep . artifacts/build-output-*/build-*.txt

  summarize-test:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report test results
        run: |
          grep . artifacts/test-output-*/test-*.txt
