---
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{matrix.os}}-${{matrix.perl}}'
    needs:
      - setup
    runs-on: '${{ matrix.os }}'
    steps:
      - id: test1
        name: Get Perl Version
        run: "perl -v > build-output-${{strategy.job-index}}.txt\n"
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          if-no-files-found: error
          name: 'build-output-${{strategy.job-index}}'
          path: 'build-output-${{strategy.job-index}}.txt'
          retention-days: 1
    strategy:
      matrix: '${{ fromJSON(needs.setup.outputs.matrix) }}'
  setup:
    outputs:
      matrix: '${{ steps.matrix.outputs.matrix }}'
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest", "windows-2019"],
              "perl": ["5.38.0", "5.36.0"]
            }
        id: matrix
        run: "jq -rn 'env.DATA | fromjson | @json \"matrix=\\(.)\"' > $GITHUB_OUTPUT\n"
  summarize-build:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report build results
        run: "grep . artifacts/build-output-*/build-*.txt\n"
  summarize-test:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report test results
        run: "grep . artifacts/test-output-*/test-*.txt\n"
  test:
    concurrency:
      cancel-in-progress: true
      group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{matrix.os}}-${{matrix.perl}}'
    needs:
      - setup
      - build
    runs-on: '${{ matrix.os }}'
    steps:
      - id: test1
        name: Pretend we are doing something
        run: "echo '${{matrix.os}}:${{matrix.perl}} ......... ok' > test-output-${{strategy.job-index}}.txt\n"
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          if-no-files-found: error
          name: 'test-output-${{strategy.job-index}}'
          path: 'test-output-${{strategy.job-index}}.txt'
          retention-days: 1
    strategy:
      matrix: '${{ fromJSON(needs.setup.outputs.matrix) }}'
name: Matrix Results V2
on:
  pull_request: ~
  push:
    branches:
      - main
      - master
  workflow_dispatch: ~
