name: Mega Matrix CI # Related to SO: https://stackoverflow.com/questions/72537896/github-actions-create-matrix-of-multiple-sequential-jobs

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common-matrix-job:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs: 
      os: ${{ steps.environments.outputs.os }}
    steps:
      - name: Generate Matrix
        id: matrix
        env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest", "windows-2019"],
              "perl": ["5.38.0", "5.36.0"]
            }
        run: |
          jq -rn 'env.DATA | fromjson | @json "matrix=\(.)"' > $GITHUB_OUTPUT
  reusable:
    needs: [common-matrix-job]
    strategy:
      matrix:
        os: ${{ fromJSON(needs.common-matrix-job.outputs.matrix) }}
      fail-fast: true
      max-parallel: 1
    # environment:
    #   name: ${{ matrix.environment }}
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      os: ${{ matrix.os }}

  common-job:
    needs: 
      - common-matrix-job
      - reusable
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
