name: Mega Matrix CI # Related to SO: https://stackoverflow.com/questions/72537896/github-actions-create-matrix-of-multiple-sequential-jobs

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common-matrix-job:
    runs-on: ubuntu-latest
    outputs: 
      os: ${{ steps.environments.outputs.os }}
    steps:
      - name: Build Environments Array
        id: environments
        run: |
          osArray=()
          osArray+=("windows-2019")
          osArray+=("ubuntu-latest")
          osArray+=("macos-latest")
          osArray=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${osArray[@]}")
          echo "Updated environments list: $osArray"
          echo "os=$osArray" >> $GITHUB_OUTPUT
        shell: bash
  
  reusable:
    needs: [common-matrix-job]
    strategy:
      matrix:
        os: ${{ fromJSON(needs.common-matrix-job.outputs.os) }}
      fail-fast: true
      max-parallel: 1
    # environment:
    #   name: ${{ matrix.environment }}
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      stage: ${{ matrix.os }}

  common-job:
    needs: 
      - common-matrix-job
      - reusable
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
