---
jobs:
  meta:
    name: '${{matrix.os}}/v${{matrix.perl}}'
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        flags: '${{ fromJSON(needs.setup.outputs.matrix).flags }}'
        os: '${{ fromJSON(needs.setup.outputs.matrix).os }}'
        perl: '${{ fromJSON(needs.setup.outputs.matrix).perl }}'
      max-parallel: 5
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      flags: '${{ matrix.flags }}'
      os: '${{ matrix.os }}'
      perl: '${{ matrix.perl }}'
  results:
    name: Results
    needs:
      - meta
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
      - name: Download test results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report test results
        run: "grep . artifacts/test-output-*/test-*.txt\n"
  setup:
    name: Generate Testing Matrix
    outputs:
      matrix: '${{ steps.matrix.outputs.matrix }}'
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest", "windows-2019"],
              "perl": ["5.38.0", "5.36.0"],
              "flags": ["", "--64int", "--thread", "--ld", "--multi", "-Dusequadmath"]
            }
        id: matrix
        run: "jq -rn 'env.DATA | fromjson | @json \"matrix=\\(.)\"' > $GITHUB_OUTPUT\n"

name: Mega Matrix CI
on:
  push: ~
  workflow_dispatch: ~
