name: Mega Matrix CI # Related to SO: https://stackoverflow.com/questions/72537896/github-actions-create-matrix-of-multiple-sequential-jobs

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest", "windows-2019"],
              "perl": ["5.38.0", "5.36.0"]
            }
        run: |
          jq -rn 'env.DATA | fromjson | @json "matrix=\(.)"' > $GITHUB_OUTPUT     
  
  build:
    needs:
      - setup
    strategy:
      matrix:
        os:  ${{ fromJSON(needs.setup.outputs.matrix).os}}
        perl:  ${{ fromJSON(needs.setup.outputs.matrix).perl}}
      fail-fast: true
      max-parallel: 5
    # environment:
    #   name: ${{ matrix.environment }}
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      os: ${{ matrix.os }}

  common-job:
    needs: 
      - setup
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
