---
jobs:
  linux:
    name: 'Linux/v${{matrix.perl}}'
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        flags: '${{ fromJSON(needs.setup.outputs.matrix).flags }}'
        os:
          - ubuntu-latest
        perl: '${{ fromJSON(needs.setup.outputs.matrix).perl }}'
      max-parallel: 5
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      os: '${{ matrix.os }}'
      perl: '${{ matrix.perl }}'
  macos:
    name: 'macOS/v${{matrix.perl}}'
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        flags: '${{ fromJSON(needs.setup.outputs.matrix).flags }}'
        os:
          - macos-latest
        perl: '${{ fromJSON(needs.setup.outputs.matrix).perl }}'
      max-parallel: 5
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      os: '${{ matrix.os }}'
      perl: '${{ matrix.perl }}'
  results:
    name: Results
    needs:
      - macos
      - win32
      - linux
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
      - name: Download test results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report test results
        run: "grep . artifacts/test-output-*/test-*.txt\n"
  setup:
    name: Generate Testing Matrix
    outputs:
      matrix: '${{ steps.matrix.outputs.matrix }}'
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest"],
              "perl": ["5.38.0", "5.36.0"],
              "flags": ["", "--64int", "--thread", "--ld", "--multi", "--Dusequadmath"]
            }
        id: matrix
        run: "jq -rn 'env.DATA | fromjson | @json \"matrix=\\(.)\"' > $GITHUB_OUTPUT\n"
  win32:
    name: 'Windows/v${{matrix.perl}}'
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        flags: '${{ fromJSON(needs.setup.outputs.matrix).flags }}'
        os:
          - windows-2019
        perl: '${{ fromJSON(needs.setup.outputs.matrix).perl }}'
      max-parallel: 5
    uses: sanko/workflow_testing/.github/workflows/windows.yml@main
    with:
      os: '${{ matrix.os }}'
      perl: '${{ matrix.perl }}'
name: Mega Matrix CI
on:
  push: ~
  workflow_dispatch: ~
