---
jobs:
  build:
    name: 'OS: ${{matrix.os}}, Perl: ${{matrix.perl}}'
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        os: '${{ fromJSON(needs.setup.outputs.matrix).os }}'
        perl: '${{ fromJSON(needs.setup.outputs.matrix).perl }}'
      max-parallel: 5
    uses: sanko/workflow_testing/.github/workflows/matrix.yml@main
    with:
      os: '${{ matrix.os }}'
      perl: '${{ matrix.perl }}'
  results:
    name: Results
    needs:
      - setup
      - build
      - win32
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
      - name: Download test results
        uses: actions/download-artifact@v4.0.0
        with:
          path: artifacts
      - name: Report test results
        run: "grep . artifacts/test-output-*/test-*.txt\n"
  setup:
    name: Generate Testing Matrix
    outputs:
      matrix: '${{ steps.matrix.outputs.matrix }}'
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest"],
              "perl": ["5.38.0", "5.36.0"]
            }
        id: matrix
        run: "jq -rn 'env.DATA | fromjson | @json \"matrix=\\(.)\"' > $GITHUB_OUTPUT\n"
  win32:
    name: 'OS: windows-2019, Perl: ${{matrix.perl}}'
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
        perl: '${{ fromJSON(needs.setup.outputs.matrix).perl }}'
      max-parallel: 5
    uses: sanko/workflow_testing/.github/workflows/windows.yml@main
    with:
      os: windows-2019
      perl: '${{ matrix.perl }}'
name: Mega Matrix CI
on:
  push: ~
  workflow_dispatch: ~
