name: Matrix module

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      perl:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Build in ${{ inputs.os }}
        run: |
          echo "Build in ${{ inputs.os }}"

  test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Test in ${{ inputs.os }}
        run: |
          echo "Test in ${{ inputs.os }}"

  deploy:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Deploy in ${{ inputs.os }}
        run: |
          echo "Deploy in ${{ inputs.os }}"
