---
jobs:
  build:
    name: "${{ inputs.flags || 'Default' }}"
    runs-on: '${{ inputs.os }}'
    steps:
      - id: cache-perl
        name: Check perl Cache
        uses: actions/cache@v4
        with:
          key: '${{ inputs.os }}-perl-v${{ inputs.perl }}${{ inputs.flags }}'
          path: '~/perl5/'
      - if: "${{  steps.cache-perl.outputs.cache-hit != 'true' && inputs.os == 'windows-2019' }}"
        name: Init dev env on Windows
        run: |
          # skip installing perl if it is already installed.
          if (!(Test-Path "C:\strawberry\perl\bin")) {
            choco install strawberryperl
          }
          echo @"
          C:\strawberry\c\bin
          C:\strawberry\perl\site\bin
          C:\strawberry\perl\bin
          "@ |
            Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - if: "${{ steps.cache-perl.outputs.cache-hit != 'true' }}"
        name: 'Build perl ${{ inputs.perl }} from source'
        shell: bash
        run: |
          git clone --depth 1 --branch v${{inputs.perl}} https://github.com/Perl/perl5.git

          if [[ ${{ runner.os }} == 'Windows' ]]; then
            pushd perl5/win32
            gmake CCHOME=C:/strawberry/c INST_TOP="C:\Users\runneradmin\perl5\perlbrew"  ${{
              inputs.flags == '-Dusethreads'    && 'USE_ITHREADS=define    USE_MULTI=define' || '' }} ${{
              inputs.flags == '-Duselongdouble' && 'USE_LONG_DOUBLE=define'                  || '' }} ${{
              inputs.flags == '-Dusequadmath'   && 'USE_QUADMATH=define'                     || '' }} -f GNUMakefile -j5 install
          else
            pushd perl5
            sh Configure -de ${{ inputs.flags }}
            make -j5
            make install
          fi

          popd
      - id: version
        name: Report Perl Version
        run: |
          ${{ runner.os == 'Windows' &&
          '[Environment]::SetEnvironmentVariable("PATH", "C:\Users\runneradmin\perl5\bin;$env:PATH")' ||
          'export PATH=~/perl5/bin:$PATH' }}

          perl -V

          perl -e 'print $^V' > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
      - name: Try it again...
        run: perl -V
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          if-no-files-found: error
          name: 'test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}'
          path: 'test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt'
          retention-days: 1
name: Matrix module
on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
