---
jobs:
  build:
    name: "${{ inputs.flags || 'Default' }}"
    runs-on: '${{ inputs.os }}'
    steps:
      - id: cache-perl
        name: Check perl Cache
        uses: actions/cache@v4
        with:
          key: '${{ inputs.os }}-perl-v${{ inputs.perl }}${{ inputs.flags }}'
          path: '~/perl5/perlbrew/'
      - if: "${{  steps.cache-perl.outputs.cache-hit != 'true' && inputs.os == 'windows-2019' }}"
        name: Init dev env on Windows
        run: |
          # skip installing perl if it is already installed.
          if (!(Test-Path "C:\strawberry\perl\bin")) {
            choco install strawberryperl
          }
          echo @"
          C:\strawberry\c\bin
          C:\strawberry\perl\site\bin
          C:\strawberry\perl\bin
          "@ |
            Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - if: "${{ steps.cache-perl.outputs.cache-hit != 'true' && inputs.os == 'windows-2019' }}"
        name: 'Build perl ${{ inputs.perl }} from source on Windows'
        run: |
          git clone --depth 1 --branch v${{inputs.perl}} https://github.com/Perl/perl5.git
          pushd perl5\win32
          
          gmake CCHOME=C:\strawberry\c INST_TOP="C:\Users\runneradmin\perl5\perlbrew"  ^
              ${{ inputs.flags == '--64int'        && 'USE_64_BIT_INT=define'                   || '' }} ^
              ${{ inputs.flags == '--thread'       && 'USE_ITHREADS=define    USE_MULTI=define' || '' }} ^
              ${{ inputs.flags == '--ld'           && 'USE_LONG_DOUBLE=define'                  || '' }} ^
              ${{ inputs.flags == '--multi'        && 'USE_MULTI=define'                        || '' }} ^
              ${{ inputs.flags == '-Dusequadmath'  && 'USE_QUADMATH=define'                     || '' }} ^
              ${{ inputs.flags == '--32bit'        && 'WIN64=undef'                             || '' }} ^
              -f GNUMakefile -j2 install
          
          popd
          set PATH=C:\Users\runneradmin\perl5\perlbrew\bin;%PATH%
        shell: cmd
      - if: "${{ inputs.os == 'windows-2019' }}"
        name: Install deps
        run: |
          set PATH=C:\Users\runneradmin\perl5\perlbrew\bin;%PATH%
          
          perl -V
          
          perl -v > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
        shell: cmd
      - if: "${{ steps.cache-perl.outputs.cache-hit != 'true' && inputs.os != 'windows-2019' }}"
        name: Build perl on other platforms with perlbrew
        run: |
          \curl -L https://install.perlbrew.pl | bash
          source ~/perl5/perlbrew/etc/bashrc
          perlbrew available
          perlbrew install-cpanm
          perlbrew install --switch --verbose --as cache-${{ inputs.os }}${{ inputs.perl }}${{ inputs.flags }} -j 12 --notest --noman ${{ inputs.flags }} perl-${{ inputs.perl }}
        shell: bash
      - id: perl
        if: "${{ inputs.os != 'windows-2019' }}"
        name: Get Perl Version
        run: |
          perl -V
          perl -v > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          if-no-files-found: error
          name: 'test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}'
          path: 'test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt'
          retention-days: 1
name: Matrix module
on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
