---
jobs:
  build:
    name: ${{ inputs.flags || 'Default' }}
    runs-on: '${{ inputs.os }}'
    steps:
      - name: 'Build in ${{ inputs.os }}'
        run: "echo \"Build in ${{ inputs.os }}\"\n"
      - id: cache-perl
        name: Cache perl
        uses: actions/cache@v4
        with:
          key: '${{ inputs.os }}-perl-v${{ inputs.perl }}${{ inputs.flags }}'
          path: '~/perl5/perlbrew/'
      #~ - if: "${{ steps.cache-perl.outputs.cache-hit != 'true' && inputs.os != 'windows-2019' }}"
      - name: 'Build perl ${{ inputs.perl }} with perlbrew'
        run: |
          \curl -L https://install.perlbrew.pl | bash
          source ~/perl5/perlbrew/etc/bashrc

          perlbrew available
          perlbrew install-cpanm

          perlbrew install --switch --verbose --as cache-${{ inputs.os }}${{ inputs.perl }}${{ inputs.flags }} -j 12 --notest --noman ${{ inputs.flags }} perl-${{ inputs.perl }}
        shell: bash
      - id: perl
        name: Get Perl Version
        run: "perl -v > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt\n"
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          if-no-files-found: error
          name: 'test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}'
          path: 'test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt'
          retention-days: 1
name: Windows
on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
